### ISSUE TITLE
ToHex() does not exist

### ISSUE THREAD

**Issue by Lexus123** [muesli/gamut#17]
![image](https://user-images.githubusercontent.com/10603646/140189183-7bee2705-0b7b-45b2-b215-46606e643a23.png)

**Comment by Lexus123** [comment]
Had to fork it and create a release in order to get this functionality.

You might wanna create a new release?

**Comment by muesli** [comment]
@Lexus123 No need to fork this, you can simply pin the dep to a specific commit or branch, e.g:

```bash
go get github.com/muesli/gamut@master
```
