### ISSUE TITLE
HueOffset() failed in case of 180°

### ISSUE THREAD

**Issue by printmaps** [muesli/gamut#8]
Not correct HSL(180.0°, 100.0%, 50.0%):

<img width="895" alt="Bildschirmfoto 2020-11-09 um 06 50 23" src="https://user-images.githubusercontent.com/26689799/98504787-26e5e880-2258-11eb-977b-8513dc762a63.png">

Correct HSL(179.5°, 100.0%, 50.0%):

<img width="897" alt="Bildschirmfoto 2020-11-09 um 06 49 58" src="https://user-images.githubusercontent.com/26689799/98504801-2d746000-2258-11eb-9aee-2ccf6b5a5e34.png">

**Comment by muesli** [comment]
Thank you, fixed and released as `v0.1.2`.

**Comment by printmaps** [comment]
Thanks for fixing this.

<img width="881" alt="Bildschirmfoto 2020-11-10 um 17 49 02" src="https://user-images.githubusercontent.com/26689799/98704537-0e232300-237d-11eb-8168-40ad891de5e4.png">
